"""initial schema

Creates the full schema from the SQLAlchemy metadata. Using ``create_all`` keeps the
DDL dialect-correct on both SQLite and PostgreSQL (JSONB vs JSON, bigint variants, etc.)
without depending on autogenerate quirks. Future changes can be autogenerated on top.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-23
"""
from alembic import op  # noqa: F401

from app.db.base import Base
from app.db import models  # noqa: F401  register tables

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
